from __future__ import annotations

from .templates import (
    DIRECT_REPLY_PROMPT,
    GLOBAL_MEMORY_CONSOLIDATION_PROMPT,
    GLOBAL_MEMORY_ROUTE_PROMPT,
    NAMESPACE_PROMPT,
    RAG_ROUTE_PROMPT,
    REFLECT_PROMPT,
    TASK_SPLIT_PROMPT,
    TASK_SYNTHESIS_PROMPT,
    WINDOW_COMPRESSION_EVALUATION_PROMPT,
    WINDOW_COMPRESSION_PROMPT,
    WINDOW_FACT_RECALL_PROMPT,
    WINDOW_MISSING_POINT_VERIFICATION_PROMPT,
    SYSTEM_PROMPT,
    TURN_ROUTE_PROMPT,
    WINDOW_MEMORY_SUMMARY_PROMPT,
)

__all__ = [
    "DIRECT_REPLY_PROMPT",
    "GLOBAL_MEMORY_CONSOLIDATION_PROMPT",
    "GLOBAL_MEMORY_ROUTE_PROMPT",
    "NAMESPACE_PROMPT",
    "RAG_ROUTE_PROMPT",
    "REFLECT_PROMPT",
    "TASK_SPLIT_PROMPT",
    "TASK_SYNTHESIS_PROMPT",
    "WINDOW_COMPRESSION_EVALUATION_PROMPT",
    "WINDOW_COMPRESSION_PROMPT",
    "WINDOW_FACT_RECALL_PROMPT",
    "WINDOW_MISSING_POINT_VERIFICATION_PROMPT",
    "SYSTEM_PROMPT",
    "TURN_ROUTE_PROMPT",
    "WINDOW_MEMORY_SUMMARY_PROMPT",
]
